version: '3'

services:
  frontend:
    build:
      context: frontend
    restart: unless-stopped    
    environment:
      NEXT_PUBLIC_BLOCK_EXPLORER: http://etherscan.io
      NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
      NEXT_PUBLIC_FACTORY_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
    ports:
      - "3000:3000"
    depends_on:
      - node
      - backend

  backend:
    build:
      context: backend
    environment:
      URL: "http://node:8545/"
      ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      PORT: 5000;
      BLOCK_AMOUNT: 2
    ports:
      - "5000:5000"
    depends_on:
      - node

  node:
    build:
      context: smart-contracts
    ports:
      - "8545:8545"
